baani/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace='homeApp')),
    path('admin/', admin.site.urls),
    path('activate/', include(('activation.urls', 'activation'), namespace='activationApp')),
    path('', include('pwa.urls')),

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .apiView import *
from .views import *

urlpatterns = [
    # pages
    path('home/', homepage, name='homepage'),
    path('', loginPage, name='loginPage'),
    path('logout/', user_logout, name='logout'),
    path('postLogin/', postLogin, name='UserLogin'),

    # collection
    path('collection_home/', collection_home, name='collection_home'),
    path('customer_home/', customer_home, name='customer_home'),
    path('customer/change-password/', customer_change_password, name='customer_change_password'),
    path('myProfile/', my_profile_collection, name='my_profile_collection'),
    path('add_collection/', add_collection, name='add_collection'),
    path('my_collection/', my_collection, name='my_collection'),
    path('api/CollectionByStaffListJson/', CollectionByStaffListJson.as_view(), name='CollectionByStaffListJson'),

    #
    # # admin
    path('my_profile/', my_profile, name='my_profile'),
    path('admin_home/', admin_home, name='admin_home'),
    path('user_list/', user_list, name='user_list'),
    path('party_group_list/', party_group_list, name='party_group_list'),
    path('party_list/', party_list, name='party_list'),
    path('bank_list/', bank_list, name='bank_list'),

    # Admin Collection
    path('take_collection/', take_collection, name='take_collection'),
    path('edit_collection/<int:id>/', edit_collection, name='edit_collection'),
    path('collection_list/', collection_list, name='collection_list'),
    path('cheque_reminder_list/', cheque_reminder_list, name='cheque_reminder_list'),
    path('api/delete_collection/', delete_collection, name='delete_collection'),
    path('api/approve_collection/', approve_collection, name='approve_collection'),
    path('api/CollectionByAdminListJson/', CollectionByAdminListJson.as_view(), name='CollectionByAdminListJson'),
    path('api/ChequeReminderCollectionListJson/', ChequeReminderCollectionListJson.as_view(),
         name='ChequeReminderCollectionListJson'),

    # # api Staff
    path('api/add_staff_api/', add_staff_api, name='add_staff_api'),
    path('api/delete_staff_user/', delete_staff_user, name='delete_staff_user'),
    path('api/get_staff_user_detail/', get_staff_user_detail, name='get_staff_user_detail'),
    path('api/edit_staff_api/', edit_staff_api, name='edit_staff_api'),
    path('api/StaffUserListJson/', StaffUserListJson.as_view(), name='StaffUserListJson'),

    # # api party group
    path('api/add_party_group_api/', add_party_group_api, name='add_party_group_api'),
    path('api/delete_part_group/', delete_part_group, name='delete_part_group'),
    path('api/get_party_group_detail/', get_party_group_detail, name='get_party_group_detail'),
    path('api/edit_part_group_api/', edit_part_group_api, name='edit_part_group_api'),
    path('api/PartyGroupListJson/', PartyGroupListJson.as_view(), name='PartyGroupListJson'),
    #
    # api Banks
    path('api/add_bank_api/', add_bank_api, name='add_bank_api'),
    path('api/BankListJson/', BankListJson.as_view(), name='BankListJson'),
    path('api/delete_bank/', delete_bank, name='delete_bank'),
    path('api/get_bank_detail/', get_bank_detail, name='get_bank_detail'),
    path('api/edit_bank_api/', edit_bank_api, name='edit_bank_api'),

    # api party
    path('api/add_party_api/', add_party_api, name='add_party_api'),
    path('api/generate_party_users_api/', generate_party_users_api, name='generate_party_users_api'),
    path('api/PartyListJson/', PartyListJson.as_view(), name='PartyListJson'),
    path('api/get_party_detail/', get_party_detail, name='get_party_detail'),
    path('api/edit_party_api/', edit_party_api, name='edit_party_api'),
    path('api/delete_party/', delete_party, name='delete_party'),
    path('api/list_party_api/', list_party_api, name='list_party_api'),
    path('api/list_party_by_executive_or_station_api/', list_party_by_executive_or_station_api,
         name='list_party_by_executive_or_station_api'),

    # Collection
    path('api/add_collection_by_staff_api/', add_collection_by_staff_api, name='add_collection_by_staff_api'),
    path('api/add_collection_by_admin_api/', add_collection_by_admin_api, name='add_collection_by_admin_api'),
    path('api/edit_collection_by_admin_api/', edit_collection_by_admin_api, name='edit_collection_by_admin_api'),

    # # change password
    path('api/change_password_api/', change_password_api, name='change_password_api'),

    path('api/get_admin_dashboard_report_api/', get_admin_dashboard_report_api, name='get_admin_dashboard_report_api'),
    path('api/get_staff_dashboard_report_api/', get_staff_dashboard_report_api, name='get_staff_dashboard_report_api'),

    #
    path('api/generate_collection_report/', generate_collection_report, name='generate_collection_report'),
    # path('get_party_data/', get_party_data, name='get_party_data'),
    path('generate_collection_date/', generate_collection_date, name='generate_collection_date'),

    # staff user
    path('staff_home/', staff_home, name='staff_home'),

    # attendance
    path('add_attendance/', add_attendance, name='add_attendance'),
    path('attendance_report/', attendance_report, name='attendance_report'),
    path('attendance_report_admin/', attendance_report_admin, name='attendance_report_admin'),
    path('api/add_attendance_api/', add_attendance_api, name='add_attendance_api'),
    path('api/generate_attendance_pdf_staff_report/', generate_attendance_pdf_staff_report,
         name='generate_attendance_pdf_staff_report'),
    path('api/generate_attendance_pdf_admin_report/', generate_attendance_pdf_admin_report,
         name='generate_attendance_pdf_admin_report'),
    path('api/StaffAttendanceListJson/', StaffAttendanceListJson.as_view(), name='StaffAttendanceListJson'),
    path('api/AdminAttendanceListJson/', AdminAttendanceListJson.as_view(), name='AdminAttendanceListJson'),

    # Sales
    path('add_sales/', add_sales, name='add_sales'),
    path('sales_list/', sales_list, name='sales_list'),
    path('my_sales_list/', my_sales_list, name='my_sales_list'),
    path('api/add_sales_by_admin_api/', add_sales_by_admin_api, name='add_sales_by_admin_api'),
    path('api/update_sales_by_admin_api/', update_sales_by_admin_api, name='update_sales_by_admin_api'),
    path('api/SalesByAdminListJson/', SalesByAdminListJson.as_view(), name='SalesByAdminListJson'),
    path('api/SalesByStaffListJson/', SalesByStaffListJson.as_view(), name='SalesByStaffListJson'),
    path('api/generate_sales_report/', generate_sales_report, name='generate_sales_report'),
    path('api/delete_sales/', delete_sales, name='delete_sales'),
    path('api/send_message_sales/', send_message_sales, name='send_message_sales'),
    path('edit_sales/<int:id>/', edit_sales, name='edit_sales'),

    # message List
    path('message_list/', message_list, name='message_list'),
    path('api/MessageListJson/', MessageListJson.as_view(), name='MessageListJson'),
    path('api/re_send_message_sales/', re_send_message_sales, name='re_send_message_sales'),
    path('api/enable_tally_post_api/', enable_tally_post_api, name='enable_tally_post_api'),

    # cashCounter
    path('cash_counter_home/', cash_counter_home, name='cash_counter_home'),
    path('cash_counter/', cash_counter, name='cash_counter'),
    path('cash_counter_collection/', cash_counter_collection, name='cash_counter_collection'),
    path('edit_cash_counter_collection/<int:id>/', edit_cash_counter_collection, name='edit_cash_counter_collection'),
    path('edit_cash_counter/<int:id>/', edit_cash_counter, name='edit_cash_counter'),
    path('my_cash_counter_list/', my_cash_counter_list, name='my_cash_counter_list'),
    path('api/add_cash_counter_entry_api/', add_cash_counter_entry_api, name='add_cash_counter_entry_api'),
    path('api/edit_cash_counter_collection_by_admin_api/', edit_cash_counter_collection_by_admin_api,
         name='edit_cash_counter_collection_by_admin_api'),
    path('api/CashCounterByStaffListJson/', CashCounterByStaffListJson.as_view(), name='CashCounterByStaffListJson'),
    path('api/CardCounterByStaffListJson/', CardCounterByStaffListJson.as_view(), name='CardCounterByStaffListJson'),
    path('api/ReturnCounterByStaffListJson/', ReturnCounterByStaffListJson.as_view(),
         name='ReturnCounterByStaffListJson'),
    path('api/CreditCounterByStaffListJson/', CreditCounterByStaffListJson.as_view(),
         name='CreditCounterByStaffListJson'),
    path('api/MixCounterByStaffListJson/', MixCounterByStaffListJson.as_view(), name='MixCounterByStaffListJson'),
    path('api/CollectionCounterByStaffListJson/', CollectionCounterByStaffListJson.as_view(),
         name='CollectionCounterByStaffListJson'),
    path('api/AdvanceCounterByStaffListJson/', AdvanceCounterByStaffListJson.as_view(),
         name='AdvanceCounterByStaffListJson'),
    path('api/ExpenseCounterByStaffListJson/', ExpenseCounterByStaffListJson.as_view(),
         name='ExpenseCounterByStaffListJson'),
    path('api/get_cash_counter_dashboard_report_api/', get_cash_counter_dashboard_report_api,
         name='get_cash_counter_dashboard_report_api'),
    path('api/get_cash_counter_dashboard_report_admin_api/', get_cash_counter_dashboard_report_admin_api,
         name='get_cash_counter_dashboard_report_admin_api'),
    path('api/delete_cash_counter/', delete_cash_counter, name='delete_cash_counter'),
    path('api/update_cash_counter_by_admin_api/', update_cash_counter_by_admin_api,
         name='update_cash_counter_by_admin_api'),
    path('api/generate_cash_counter_report/', generate_cash_counter_report, name='generate_cash_counter_report'),
    path('api/add_collection_from_cash_counter_api/', add_collection_from_cash_counter_api,
         name='add_collection_from_cash_counter_api'),
    path('api/CashCounterCollectionListJson/', CashCounterCollectionListJson.as_view(),
         name='CashCounterCollectionListJson'),

home/templates/home/admin/collectionReportPDF.html
{% load custom_has_group_tag %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BSSAC</title>
    <style>
        @page {
            size: A5;
            margin: .3cm;
        }


    </style>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td, th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 5px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="row">
        <span style="font-size: 10px;">(BSSAC) Collection Report for Date: {{ date|date }}</span>
    </div>


    <table style="font-size: 10px">
        <tr>
            <th>CollectedBy</th>
            <th>Cash(₹)</th>
            <th>Cheque CC(₹)</th>
            <th>Cheque(₹)</th>
            <th>Online(₹)</th>
            <th>Party(₹)</th>
            <th>Total(₹)</th>
        </tr>
        <tr>
            <td>{{ staffName }}</td>
            <td>{{ a_total_cash|convert }}</td>
            <td>{{ a_total_cheque_cc|convert }}</td>
            <td>{{ a_total_cheque|convert }}</td>
            <td>{{ a_total_online|convert }}</td>
            <td>{{ a_total_party|convert }}</td>
            <td>{{ total|convert }}</td>
        </tr>
    </table>
    <p style="font-size: 10px; margin: 2px;padding-top: 10px">Collection Details</p>

    <table style="font-size: 10px">
        <tr>
            <th>PaymentID</th>
            <th>PartyName</th>
            <th>Amount(₹)</th>
            <th>Type</th>
            <th>CollectedBy</th>
        </tr>
        {% for foo in col %}

            <tr>
                <td>{{ foo.paymentID }}</td>
                <td>{{ foo.partyID.name }}</td>
                <td>{{ foo.paidAmount|convert }}</td>
                <td>{{ foo.modeOfPayment }}</td>
                <td>{{ foo.collectedBy.name }}</td>
            </tr>
        {% endfor %}

    </table>
</div>

</body>
</html>

home/templates/home/admin/profileAdmin.html
{% extends 'home/admin/index.html' %}
{% load static %}

{% block title %}
    <title>My Profile </title>
{% endblock %}
{% block css %}

{% endblock %}
{% block body %}
    <div class="ui right aligned basic  grid">
        <div class="sixteen wide column">
            <div class="ui  pointing secondary menu">
                <div style="cursor: pointer;" class="item active" data-tab="user"
                >My Profile
                </div>
            </div>

            <div class="ui tab " data-tab="user">

                <div class="row" style="padding-left: 5px; padding-right: 5px">
                    <div class="ui placeholder segment" style="width: 100%;">
                        {% comment %}
            <a href="/ecom/editAccount/" class="editbtn"><i class="edit icon"></i></a>
{% endcomment %}
                        <div class="ui icon header">
                            <div class="inline ">
                                <img class="ui medium circular image tiny centered" id="cImg"
                                     src="{{ instance.photo.medium.url }}">
                            </div>
                            <span id="Name">{{ instance.name|capfirst }} </span>
                        </div>
                        <div class="inline">
                            <span id="username" class="ui text medium grey">{{ instance.username }}</span>
                        </div>
                        <div class="inline">
                            <span id="Phone">{{ instance.phone }}</span>
                        </div>
                        <div class="inline">
                            <span id="address" class="ui text large grey">{{ instance.address|capfirst }} </span>
                        </div>
                    </div>
                </div>
            </div>
             <div style=" position: absolute;right: 1.5rem;top: 18px;">
                    <button class="ui green mini plus button right" onclick="showUserModal()">
                        <i class="plus square outline icon"></i>
                        Change Password
                    </button>
                </div>

        </div>
    </div>


                    <div class="ui tiny modal" id="myModalUser">
                        <i class="close icon"></i>
                        <div class="header">
                            Change Password
                        </div>
                        <div class="content">

                            <form class="ui tiny form" id="addForm">{% csrf_token %}

                                  <div class="one required fields">
                                    <div class="sixteen wide field">
                                        <label>New Password</label>
                                        <input type="password" name="NewPassword" placeholder="New Password" id="newPassword">
                                    </div>

                                </div>
                                 <div class="one required fields">
                                    <div class="sixteen wide field">
                                        <label>Confirm Password</label>
                                        <input type="password" name="confirmPassword" placeholder="Confirm Password" id="confirmPassword">
                                    </div>

                                </div>

                            </form>

                            <div class="actions" style="padding-top: 20px; padding-bottom: 20px ;float: right">
                                <div class="ui cancel button">Cancel</div>
                                <button class="ui right labeled icon button green saveBtn" onclick="changePassword()">
                                    Submit
                                    <i class="checkmark icon"></i>
                                </button>
                                <button style="display: none" class="ui right labeled icon button green saveBtnLoad" >
                                    Saving ...
                                    <i class="checkmark icon"></i>
                                </button>
                            </div>
                        </div>
                    </div>
{% endblock %}

{% block js %}
    <script>

        function showUserModal() {
            $('#myModalUser').modal('show');
        }
             function changePassword() {
            showLoading();
            var pass = $('#newPassword').val();
            var passc = $('#confirmPassword').val();


            if (pass === '' || passc === "") {
                 $('body')
                    .toast({
                        class: 'orange',
                        message: '* fields are required.'
                    })
                ;
                 hideLoading();

            }

            else {
                if (pass !== passc) {
                      $('body')
                    .toast({
                        class: 'orange',
                        message: 'Password not matched.'
                    })
                ;
                      hideLoading();
                }
                else if (pass.length < 8) {
                      $('body')
                    .toast({
                        class: 'orange',
                        message: 'Password should be at least 8 characters long.'
                    })
                ;
                      hideLoading();

                }
                else {
                     var csrfmiddlewaretoken = $("input[name='csrfmiddlewaretoken']").val();

                data = new FormData();
                data.append('password', pass);


                data.append('csrfmiddlewaretoken', csrfmiddlewaretoken);


                $.ajax({
                    type: 'post',
                    url: '{% url "homeApp:change_password_api" %}',
                    data: data,
                    contentType: false,
                    cache: false,
                    processData: false,


                    success: function (response) {
                        if (response.message === 'success') {
                            $('body')
                                .toast({
                                    class: 'success',
                                    message: 'Password changed Successfully.'
                                })
                            ;


                            $('#addForm').trigger('reset');
                            $('#myModalUser').modal('toggle');
                            hideLoading();
                        } else {
                            $('body')
                                .toast({
                                    class: 'error',
                                    message: 'An error occurred !'
                                })
                            ;
                            hideLoading();

                        }

                        return response;
                    },
                    error: function () {
                        $('body')
                            .toast({
                                class: 'error',
                                message: 'An error occurred !'
                            })
                        ;
                        hideLoading();


            }
           });
            }
            }
             }



    </script>
{% endblock %}