baani/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('home.urls', 'home'), namespace='homeApp')),
    path('admin/', admin.site.urls),
    path('activate/', include(('activation.urls', 'activation'), namespace='activationApp')),
    path('', include('pwa.urls')),

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from .apiView import *
from .views import *

urlpatterns = [
    # pages
    path('home/', homepage, name='homepage'),
    path('', loginPage, name='loginPage'),
    path('logout/', user_logout, name='logout'),
    path('postLogin/', postLogin, name='UserLogin'),

    # collection
    path('collection_home/', collection_home, name='collection_home'),
    path('customer_home/', customer_home, name='customer_home'),
    path('customer/change-password/', customer_change_password, name='customer_change_password'),
    path('myProfile/', my_profile_collection, name='my_profile_collection'),
    path('add_collection/', add_collection, name='add_collection'),
    path('my_collection/', my_collection, name='my_collection'),
    path('api/CollectionByStaffListJson/', CollectionByStaffListJson.as_view(), name='CollectionByStaffListJson'),

    #
    # # admin
    path('my_profile/', my_profile, name='my_profile'),
    path('admin_home/', admin_home, name='admin_home'),
    path('user_list/', user_list, name='user_list'),
    path('party_group_list/', party_group_list, name='party_group_list'),
    path('party_list/', party_list, name='party_list'),
    path('bank_list/', bank_list, name='bank_list'),

    # Admin Collection
    path('take_collection/', take_collection, name='take_collection'),
    path('edit_collection/<int:id>/', edit_collection, name='edit_collection'),
    path('collection_list/', collection_list, name='collection_list'),
    path('cheque_reminder_list/', cheque_reminder_list, name='cheque_reminder_list'),
    path('api/delete_collection/', delete_collection, name='delete_collection'),
    path('api/approve_collection/', approve_collection, name='approve_collection'),
    path('api/CollectionByAdminListJson/', CollectionByAdminListJson.as_view(), name='CollectionByAdminListJson'),
    path('api/ChequeReminderCollectionListJson/', ChequeReminderCollectionListJson.as_view(),
         name='ChequeReminderCollectionListJson'),

    # # api Staff
    path('api/add_staff_api/', add_staff_api, name='add_staff_api'),
    path('api/delete_staff_user/', delete_staff_user, name='delete_staff_user'),
    path('api/get_staff_user_detail/', get_staff_user_detail, name='get_staff_user_detail'),
    path('api/edit_staff_api/', edit_staff_api, name='edit_staff_api'),
    path('api/StaffUserListJson/', StaffUserListJson.as_view(), name='StaffUserListJson'),

    # # api party group
    path('api/add_party_group_api/', add_party_group_api, name='add_party_group_api'),
    path('api/delete_part_group/', delete_part_group, name='delete_part_group'),
    path('api/get_party_group_detail/', get_party_group_detail, name='get_party_group_detail'),
    path('api/edit_part_group_api/', edit_part_group_api, name='edit_part_group_api'),
    path('api/PartyGroupListJson/', PartyGroupListJson.as_view(), name='PartyGroupListJson'),
    #
    # api Banks
    path('api/add_bank_api/', add_bank_api, name='add_bank_api'),
    path('api/BankListJson/', BankListJson.as_view(), name='BankListJson'),
    path('api/delete_bank/', delete_bank, name='delete_bank'),
    path('api/get_bank_detail/', get_bank_detail, name='get_bank_detail'),
    path('api/edit_bank_api/', edit_bank_api, name='edit_bank_api'),

    # api party
    path('api/add_party_api/', add_party_api, name='add_party_api'),
    path('api/generate_party_users_api/', generate_party_users_api, name='generate_party_users_api'),
    path('api/PartyListJson/', PartyListJson.as_view(), name='PartyListJson'),
    path('api/get_party_detail/', get_party_detail, name='get_party_detail'),
    path('api/edit_party_api/', edit_party_api, name='edit_party_api'),
    path('api/delete_party/', delete_party, name='delete_party'),
    path('api/list_party_api/', list_party_api, name='list_party_api'),
    path('api/list_party_by_executive_or_station_api/', list_party_by_executive_or_station_api,
         name='list_party_by_executive_or_station_api'),

    # Collection
    path('api/add_collection_by_staff_api/', add_collection_by_staff_api, name='add_collection_by_staff_api'),
    path('api/add_collection_by_admin_api/', add_collection_by_admin_api, name='add_collection_by_admin_api'),
    path('api/edit_collection_by_admin_api/', edit_collection_by_admin_api, name='edit_collection_by_admin_api'),

    # # change password
    path('api/change_password_api/', change_password_api, name='change_password_api'),

    path('api/get_admin_dashboard_report_api/', get_admin_dashboard_report_api, name='get_admin_dashboard_report_api'),
    path('api/get_staff_dashboard_report_api/', get_staff_dashboard_report_api, name='get_staff_dashboard_report_api'),

    #
    path('api/generate_collection_report/', generate_collection_report, name='generate_collection_report'),
    # path('get_party_data/', get_party_data, name='get_party_data'),
    path('generate_collection_date/', generate_collection_date, name='generate_collection_date'),

    # staff user
    path('staff_home/', staff_home, name='staff_home'),

    # attendance
    path('add_attendance/', add_attendance, name='add_attendance'),
    path('attendance_report/', attendance_report, name='attendance_report'),
    path('attendance_report_admin/', attendance_report_admin, name='attendance_report_admin'),
    path('api/add_attendance_api/', add_attendance_api, name='add_attendance_api'),
    path('api/generate_attendance_pdf_staff_report/', generate_attendance_pdf_staff_report,
         name='generate_attendance_pdf_staff_report'),
    path('api/generate_attendance_pdf_admin_report/', generate_attendance_pdf_admin_report,
         name='generate_attendance_pdf_admin_report'),
    path('api/StaffAttendanceListJson/', StaffAttendanceListJson.as_view(), name='StaffAttendanceListJson'),
    path('api/AdminAttendanceListJson/', AdminAttendanceListJson.as_view(), name='AdminAttendanceListJson'),

    # Sales
    path('add_sales/', add_sales, name='add_sales'),
    path('sales_list/', sales_list, name='sales_list'),
    path('my_sales_list/', my_sales_list, name='my_sales_list'),
    path('api/add_sales_by_admin_api/', add_sales_by_admin_api, name='add_sales_by_admin_api'),
    path('api/update_sales_by_admin_api/', update_sales_by_admin_api, name='update_sales_by_admin_api'),
    path('api/SalesByAdminListJson/', SalesByAdminListJson.as_view(), name='SalesByAdminListJson'),
    path('api/SalesByStaffListJson/', SalesByStaffListJson.as_view(), name='SalesByStaffListJson'),
    path('api/generate_sales_report/', generate_sales_report, name='generate_sales_report'),
    path('api/delete_sales/', delete_sales, name='delete_sales'),
    path('api/send_message_sales/', send_message_sales, name='send_message_sales'),
    path('edit_sales/<int:id>/', edit_sales, name='edit_sales'),

    # message List
    path('message_list/', message_list, name='message_list'),
    path('api/MessageListJson/', MessageListJson.as_view(), name='MessageListJson'),
    path('api/re_send_message_sales/', re_send_message_sales, name='re_send_message_sales'),
    path('api/enable_tally_post_api/', enable_tally_post_api, name='enable_tally_post_api'),

    # cashCounter
    path('cash_counter_home/', cash_counter_home, name='cash_counter_home'),
    path('cash_counter/', cash_counter, name='cash_counter'),
    path('cash_counter_collection/', cash_counter_collection, name='cash_counter_collection'),
    path('edit_cash_counter_collection/<int:id>/', edit_cash_counter_collection, name='edit_cash_counter_collection'),
    path('edit_cash_counter/<int:id>/', edit_cash_counter, name='edit_cash_counter'),
    path('my_cash_counter_list/', my_cash_counter_list, name='my_cash_counter_list'),
    path('api/add_cash_counter_entry_api/', add_cash_counter_entry_api, name='add_cash_counter_entry_api'),
    path('api/edit_cash_counter_collection_by_admin_api/', edit_cash_counter_collection_by_admin_api,
         name='edit_cash_counter_collection_by_admin_api'),
    path('api/CashCounterByStaffListJson/', CashCounterByStaffListJson.as_view(), name='CashCounterByStaffListJson'),
    path('api/CardCounterByStaffListJson/', CardCounterByStaffListJson.as_view(), name='CardCounterByStaffListJson'),
    path('api/ReturnCounterByStaffListJson/', ReturnCounterByStaffListJson.as_view(),
         name='ReturnCounterByStaffListJson'),
    path('api/CreditCounterByStaffListJson/', CreditCounterByStaffListJson.as_view(),
         name='CreditCounterByStaffListJson'),
    path('api/MixCounterByStaffListJson/', MixCounterByStaffListJson.as_view(), name='MixCounterByStaffListJson'),
    path('api/CollectionCounterByStaffListJson/', CollectionCounterByStaffListJson.as_view(),
         name='CollectionCounterByStaffListJson'),
    path('api/AdvanceCounterByStaffListJson/', AdvanceCounterByStaffListJson.as_view(),
         name='AdvanceCounterByStaffListJson'),
    path('api/ExpenseCounterByStaffListJson/', ExpenseCounterByStaffListJson.as_view(),
         name='ExpenseCounterByStaffListJson'),
    path('api/get_cash_counter_dashboard_report_api/', get_cash_counter_dashboard_report_api,
         name='get_cash_counter_dashboard_report_api'),
    path('api/get_cash_counter_dashboard_report_admin_api/', get_cash_counter_dashboard_report_admin_api,
         name='get_cash_counter_dashboard_report_admin_api'),
    path('api/delete_cash_counter/', delete_cash_counter, name='delete_cash_counter'),
    path('api/update_cash_counter_by_admin_api/', update_cash_counter_by_admin_api,
         name='update_cash_counter_by_admin_api'),
    path('api/generate_cash_counter_report/', generate_cash_counter_report, name='generate_cash_counter_report'),
    path('api/add_collection_from_cash_counter_api/', add_collection_from_cash_counter_api,
         name='add_collection_from_cash_counter_api'),
    path('api/CashCounterCollectionListJson/', CashCounterCollectionListJson.as_view(),
         name='CashCounterCollectionListJson'),

home/templates/home/sales/addSales.html
{% extends 'home/admin/index.html' %}
{% load static %}
{% load custom_has_group_tag %}

{% block title %}
    <title>Add Sales</title>
{% endblock %}
{% block css %}
    <style>
        .avatar-upload {
            position: relative;
            max-width: 115px;
            margin: 5px auto;
        }

        .avatar-upload .avatar-edit {
            position: absolute;
            right: 12px;
            z-index: 1;
            top: 10px;
        }

        .avatar-upload .avatar-edit input {
            display: none;
        }

        .avatar-upload .avatar-edit input + label {
            display: inline-block;
            width: 25px;
            height: 25px;
            margin-bottom: 0;
            border-radius: 100%;
            background: #FFFFFF;
            border: 1px solid transparent;
            box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.12);
            cursor: pointer;
            font-weight: normal;
            transition: all 0.2s ease-in-out;
        }

        .avatar-upload .avatar-edit input + label:hover {
            background: #f1f1f1;
            border-color: #d6d6d6;
        }

        .avatar-upload .avatar-edit input + label:after {
            color: #757575;
            position: absolute;
            top: 10px;
            left: 0;
            right: 0;
            text-align: center;
            margin: auto;

        }

        .avatar-upload .avatar-preview {
            width: 100px;
            height: 100px;
            position: relative;
            border-radius: 100%;
            border: 6px solid #F8F8F8;
            box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.1);
        }

        .avatar-upload .avatar-preview > div {
            width: 100%;
            height: 100%;
            border-radius: 100%;
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
        }

    </style>
{% endblock %}
{% block body %}

    <div class="ui aligned basic  grid">
        <div class="sixteen wide column">
            <div class="ui  pointing secondary menu">
                <div style="cursor: pointer;" class="item active" data-tab="user"
                >Add Sale
                </div>
            </div>
            <div class="ui tab " data-tab="user">

                <div class="ui row teal stacked segment padded">
                    <div class="content">

                        <form class="ui  small form " id="addForm">{% csrf_token %}
                            <div class="two fields">
                                <div class="eight wide field required">
                                    <label>Invoice Number</label>

                                    <div class="ui left labeled  input">
                                        <div class="ui dropdown teal label" id="invoiceSeries">
                                            <div class="text" id="invoiceSeriesSelect">BCS</div>
                                            <i class="dropdown icon"></i>
                                            <div class="menu">
                                                <div class="item">BCS</div>
                                                <div class="item">BCS1</div>
                                                <div class="item">BSS</div>
                                                <div class="item">ND</div>
                                            </div>
                                        </div>
                                        <input type="number" placeholder="Invoice Number" id="invoiceNo"
                                               name="invoiceNo">
                                        <div class="ui dropdown blue label" id="invoiceYear">
                                            <div class="text" id="invoiceYearSelect">25-26</div>
                                            <i class="dropdown icon"></i>
                                            <div class="menu">
                                                <div class="item">25-26</div>
                                                <div class="item">24-25</div>
                                                <div class="item">23-24</div>
                                                <div class="item">22-23</div>

                                            </div>
                                        </div>

                                    </div>

                                </div>


                                <div class="eight wide field required">
                                    <label>Invoice Date</label>
                                    <div class="ui calendar" id="cDate">
                                        <div class="ui input">
                                            <input type="text" placeholder="Date/Time" id="colDate">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="two  fields">
                                <div class="eight wide field required">
                                    <label>Party Name</label>
                                    <select class="ui clearable search dropdown" id="party">
                                        <option value="">Search By Party Name</option>
                                    </select>
                                </div>
                                <div class="eight wide field required">
                                    <label>Amount (₹ <a class="ui violet label" id="money">0.0</a>
                                        )</label>
                                    <input type="number" name="amount" id="amount" placeholder="Amount"
                                           onkeyup="toIndianCurrency()">


                                </div>

                            </div>


                            <div class="one  fields ">

                                <div class="sixteen wide  field ">
                                    <label>Remark</label>
                                    <textarea name="" id="remark" placeholder="Any Remark"
                                              rows="3"></textarea>
                                </div>


                            </div>


                        </form>
                    </div>
                    <div class="ui  aligned basic  grid">
                        <div class="row" style="padding-left: 5px;padding-right: 5px">
                            <div class="16 wide column center aligned">
                                <button onclick="salesSave()" id="saveBtn" class="ui green  button saveBtn">
                                    Submit Detail
                                </button>
                                <button style="display: none;" class="ui teal double loading button saveBtnLoad">
                                    Saving ....
                                </button>
                            </div>
                        </div>
                    </div>


                </div>


            </div>
        </div>


    </div>

    <input type="hidden" id="lat" value="24.809611">
    <input type="hidden" id="lng" value="93.935577">
    <input type="hidden" id="loc" value="N/A">

    <p id="demo"></p>


{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('.ui.dropdown').dropdown({fullTextSearch: true});
    </script>

    <script>
        var today = new Date();
        $('#cDate')
            .calendar({
                    initialDate: today.getDate() + '/' + (today.getMonth() + 1) + '/' + today.getFullYear(),
                    monthFirst: false,
                    type: 'date',
                    formatter: {
                        date: function (date, settings) {

                            if (!date) return '';
                            var day = String(date.getDate());
                            var month = String(date.getMonth() + 1);
                            var year = date.getFullYear();
                            {#                            return '{{ sale.invoiceDate|date:'d/m/Y' }}';#}
                            return day + '/' + month + '/' + year;
                        }
                    }
                }
            );


        function salesSave() {
            showLoading();
            var invoiceSeriesSelect = $('#invoiceSeriesSelect').html();
            var invoiceNo = $('#invoiceNo').val();
            var invoiceYearSelect = $('#invoiceYearSelect').html();
            var colDate = $('#colDate').val();
            var party = $('#party').val();
            var amount = $('#amount').val();
            var remark = $('#remark').val();


            debugger;

            if (party === '' || invoiceSeriesSelect === '' || invoiceNo === '' || invoiceYearSelect === '' || colDate === '' || amount === ''
            ) {
                $('body')
                    .toast({
                        class: 'orange',
                        message: '* fields are required !'
                    })
                ;
                hideLoading();
            } else {
                data = new FormData();
                data.append('invoiceSeriesSelect', invoiceSeriesSelect);
                data.append('invoiceNo', invoiceNo);
                data.append('invoiceYearSelect', invoiceYearSelect);
                data.append('colDate', colDate);
                data.append('party', party);
                data.append('amount', amount);
                data.append('remark', remark);

                $.ajax({
                    type: 'post',
                    url: '{% url 'homeApp:add_sales_by_admin_api' %}',
                    data: data,
                    contentType: false,
                    cache: false,
                    processData: false,


                    success: function (response) {
                        if (response.message === 'success') {
                            $('body')
                                .toast({
                                    class: 'success',
                                    message: 'Sales added Successfully.'
                                });

                            hideLoading();

                            {% if request.user|has_group:"Admin" or request.user|has_group:"Moderator" %}
                                location.href = "{% url 'homeApp:sales_list' %}"
                            {% else %}
                                location.href = "{% url 'homeApp:my_sales_list' %}"
                            {% endif %}

                        } else {
                            $('body')
                                .toast({
                                    class: 'error',
                                    message: 'An error occurred !'
                                })
                            ;
                            hideLoading();
                        }

                        return response;
                    },
                    error: function () {
                        $('body')
                            .toast({
                                class: 'error',
                                message: 'An error occurred !'
                            })
                        ;
                        hideLoading();
                    }

                });


            }

        }


        $(getCustomerList());


        function getCustomerList() {
            $.ajax({
                type: 'get',
                url: "{% url 'homeApp:list_party_api' %}",

                success: function (response) {

                    $('#party').html('');
                    $('#party').append(' <option value="">Search By Party Name</option>');
                    var j;
                    for (j = 0; j < response.data.length; j++) {

                        $('#party').append('<option value="' + response.data[j]['Detail'] + '" >' + response.data[j]['DisplayDetail'] + '</option>');

                    }

                },

                error: function () {
                    $('body')
                        .toast({
                            class: 'error',
                            message: 'An error occurred !'
                        })
                    ;
                }
            });


        }

        const toIndianCurrency = () => {
            let num = $('#amount').val();
            const curr = num.replace(/(\d)(?=(\d\d)+\d$)/g, "$1,")
            $('#money').html(curr);
        };
    </script>
{% endblock %}